import pytest
import polars as pl

# Import the Python module generated by the Rust crate
from pyo3_partition_tree import PyPartitionTree


def make_simple_data(n: int = 8):
    X = pl.DataFrame(
        {
            "x1": list(range(n)),
            "x2": [v * 2 for v in range(n)],
        }
    )
    y = pl.DataFrame(
        {
            "y": [float(v % 3) for v in range(n)],
        }
    )
    return X, y


def test_predict_before_fit_raises():
    model = PyPartitionTree(
        max_leaves=10,
        min_samples_split=2,
        min_samples_y=1.0,
        min_samples_x=1.0,
        min_samples_xy=1.0,
        min_volume_fraction=0.0,
        max_depth=5,
        min_gain=0.0,
    )
    X, _ = make_simple_data()
    with pytest.raises(ValueError, match="Model is not fitted"):
        _ = model.predict(X)


def test_fit_and_predict_returns_dataframe_with_expected_shape_and_columns():
    X, y = make_simple_data(12)
    model = PyPartitionTree(
        max_leaves=50,
        min_samples_split=2,
        min_samples_y=1.0,
        min_samples_x=1.0,
        min_samples_xy=1.0,
        min_volume_fraction=0.0,
        max_depth=10,
        min_gain=0.0,
    )
    model.fit(X, y, None)
    preds = model.predict(X)
    # Should be a polars DataFrame
    assert isinstance(preds, pl.DataFrame)
    # Row count preserved
    assert preds.height == X.height
    # predict returns a DataFrame with the same columns as y
    assert set(preds.columns) == set(y.columns), preds.columns


def test_fit_with_mismatched_row_counts_raises():
    X, y = make_simple_data(6)
    # Drop a row from y to mismatch
    y_bad = y.head(5)
    model = PyPartitionTree(
        max_leaves=10,
        min_samples_split=2,
        min_samples_y=1.0,
        min_samples_x=1.0,
        min_samples_xy=1.0,
        min_volume_fraction=0.0,
        max_depth=5,
        min_gain=0.0,
    )
    with pytest.raises(ValueError):
        model.fit(X, y_bad, None)
