import pytest
import polars as pl

# Import the Python module generated by the Rust crate
from partition_tree_python import PyPartitionTree


def make_simple_data(n: int = 8):
    X = pl.DataFrame(
        {
            "x1": list(range(n)),
            "x2": [v * 2 for v in range(n)],
        }
    )
    y = pl.DataFrame(
        {
            "y": [float(v % 3) for v in range(n)],
        }
    )
    return X, y


def test_predict_before_fit_raises():
    model = PyPartitionTree(
        max_iter=10,
        min_samples_split=2,
        min_samples_leaf_y=1,
        min_samples_leaf_x=1,
        min_samples_leaf=1,
        min_target_volume=0.0,
        max_depth=5,
        min_split_gain=0.0,
    )
    X, _ = make_simple_data()
    with pytest.raises(ValueError, match="Model is not fitted"):
        _ = model.predict(X)


def test_fit_and_predict_returns_dataframe_with_expected_shape_and_columns():
    X, y = make_simple_data(12)
    model = PyPartitionTree(
        max_iter=50,
        min_samples_split=2,
        min_samples_leaf_y=1,
        min_samples_leaf_x=1,
        min_samples_leaf=1,
        min_target_volume=0.0,
        max_depth=10,
        min_split_gain=0.0,
    )
    model.fit(X, y)
    preds = model.predict(X)
    # Should be a polars DataFrame
    assert isinstance(preds, pl.DataFrame)
    # Row count preserved
    assert preds.height == X.height
    # Expect target column to be renamed with prefix target_
    assert any(col.startswith("target_") for col in preds.columns), preds.columns


def test_fit_with_mismatched_row_counts_raises():
    X, y = make_simple_data(6)
    # Drop a row from y to mismatch
    y_bad = y.head(5)
    model = PyPartitionTree(
        max_iter=10,
        min_samples_split=2,
        min_samples_leaf_y=1,
        min_samples_leaf_x=1,
        min_samples_leaf=1,
        min_target_volume=0.0,
        max_depth=5,
        min_split_gain=0.0,
    )
    with pytest.raises(ValueError):
        model.fit(X, y_bad)
