import pickle

import pytest
import polars as pl

# Import the Python module generated by the Rust crate
from pyo3_partition_tree import Domain, PyPartitionTree


def make_simple_data(n: int = 8):
    X = pl.DataFrame(
        {
            "x1": list(range(n)),
            "x2": [v * 2 for v in range(n)],
        }
    )
    y = pl.DataFrame(
        {
            "y": [float(v % 3) for v in range(n)],
        }
    )
    X = X.cast(pl.Float64)
    y = y.cast(pl.Float64)
    return X, y


def test_predict_before_fit_raises():
    model = PyPartitionTree(
        max_leaves=10,
        min_samples_split=2,
        min_samples_y=1,
        min_samples_x=1,
        min_samples_xy=1,
        min_volume_fraction=0.0,
        max_depth=5,
        min_gain=0.0,
        boundaries_expansion_factor=0,
    )
    X, _ = make_simple_data()
    with pytest.raises(ValueError, match="Model is not fitted"):
        _ = model.predict(X)


def test_fit_and_predict_returns_dataframe_with_expected_shape_and_columns():
    X, y = make_simple_data(12)
    model = PyPartitionTree(
        max_leaves=50,
        min_samples_split=2,
        min_samples_y=1,
        min_samples_x=1,
        min_samples_xy=1,
        min_volume_fraction=0.0,
        max_depth=10,
        min_gain=0.0,
        boundaries_expansion_factor=0,
    )
    model.fit(X, y, None)
    preds = model.predict(X)
    # Should be a polars DataFrame
    assert isinstance(preds, pl.DataFrame)
    # Row count preserved
    assert preds.height == X.height


def test_fit_with_mismatched_row_counts_raises():
    X, y = make_simple_data(6)
    # Drop a row from y to mismatch
    y_bad = y.head(5)
    model = PyPartitionTree(
        max_leaves=10,
        min_samples_split=2,
        min_samples_y=1,
        min_samples_x=1,
        min_samples_xy=1,
        min_volume_fraction=0.0,
        max_depth=5,
        min_gain=0.0,
        boundaries_expansion_factor=0,
    )
    with pytest.raises(ValueError):
        model.fit(X, y_bad, None)


def test_pickle_unfitted_model():
    """Test that an unfitted PyPartitionTree can be pickled and unpickled."""
    model = PyPartitionTree(
        max_leaves=10,
        min_samples_split=2,
        min_samples_y=1,
        min_samples_x=1,
        min_samples_xy=1,
        min_volume_fraction=0.0,
        max_depth=5,
        min_gain=0.0,
        boundaries_expansion_factor=0,
    )
    # Pickle and unpickle
    pickled = pickle.dumps(model)
    unpickled_model = pickle.loads(pickled)

    # Verify the unpickled model is a PyPartitionTree
    assert isinstance(unpickled_model, PyPartitionTree)


def test_pickle_fitted_model():
    """Test that a fitted PyPartitionTree can be pickled and unpickled, and predictions match."""
    X, y = make_simple_data(12)
    model = PyPartitionTree(
        max_leaves=50,
        min_samples_split=2,
        min_samples_y=1,
        min_samples_x=1,
        min_samples_xy=1,
        min_volume_fraction=0.0,
        max_depth=10,
        min_gain=0.0,
        boundaries_expansion_factor=0,
    )
    model.fit(X, y, None)

    # Get predictions before pickling
    preds_before = model.predict(X)

    # Pickle and unpickle
    pickled = pickle.dumps(model)
    unpickled_model = pickle.loads(pickled)

    # Verify the unpickled model is a PyPartitionTree
    assert isinstance(unpickled_model, PyPartitionTree)

    # Verify predictions match after unpickling
    preds_after = unpickled_model.predict(X)
    assert preds_before.equals(preds_after)


def test_fit_accepts_dtype_override_dict_with_domain_values():
    X = pl.DataFrame(
        {
            "x1": [1.0, 2.0, 3.0, 4.0, 5.0, 6.0],
            "x2": [0.0, 0.0, 1.0, 1.0, 2.0, 2.0],
        }
    ).cast(pl.Float64)
    y = pl.DataFrame({"y": [10.0, 10.0, 20.0, 20.0, 30.0, 30.0]}).cast(pl.Float64)

    model = PyPartitionTree(
        max_leaves=20,
        min_samples_split=2,
        min_samples_y=1,
        min_samples_x=1,
        min_samples_xy=1,
        min_volume_fraction=0.0,
        max_depth=5,
        min_gain=0.0,
        boundaries_expansion_factor=0,
        dtype_overrides={"x1": Domain.integer()},
    )

    model.fit(X, y, None)
    preds = model.predict(X)
    assert isinstance(preds, pl.DataFrame)
    assert preds.height == X.height


def test_fit_accepts_quantized_domain_override():
    X = pl.DataFrame({"x1": [0.0, 0.5, 1.0, 1.5, 2.0, 2.5]}).cast(pl.Float64)
    y = pl.DataFrame({"y": [10.0, 10.0, 20.0, 20.0, 30.0, 30.0]}).cast(pl.Float64)

    model = PyPartitionTree(
        max_leaves=20,
        min_samples_split=2,
        min_samples_y=1,
        min_samples_x=1,
        min_samples_xy=1,
        min_volume_fraction=0.0,
        max_depth=5,
        min_gain=0.0,
        boundaries_expansion_factor=0,
        dtype_overrides={"x1": Domain.quantized_continuous(0.5)},
    )

    model.fit(X, y, None)
    nodes = model.get_nodes_info()
    root_partitions = nodes[0]["partitions"]
    assert root_partitions["x1"]["type"] == "quantized_continuous"
    assert root_partitions["x1"]["resolution"] == pytest.approx(0.5)


def test_domain_quantized_continuous_rejects_invalid_resolution():
    with pytest.raises(ValueError, match="resolution must be finite and positive"):
        Domain.quantized_continuous(0.0)


def test_invalid_dtype_override_value_raises():
    with pytest.raises(TypeError, match="must be a Domain"):
        PyPartitionTree(dtype_overrides={"x1": "integer"})
